resolver: lts-22.11

packages:
- .

extra-deps:
- telegram-bot-api-7.0
- telegram-bot-simple-0.13
- git: https://github.com/MichaelXavier/cron
  commit: d9193309bd06b04607898212f9c477af4894c021

# nix:
#   enable: true
#   packages: [pkg-config libffi pcre zlib]
